import type { GameManifest } from '../../shared/contracts';

export const allGameManifests: GameManifest[] = [
  {
    id: 'tic-tac-toe',
    name: 'Tic Tac Toe',
    category: 'board',
    shortDescription: 'Classic 3x3 strategy duel with instant restarts.',
    description: 'Fast, replayable three-in-a-row matches with AI hooks, hotseat play, and tutorial support.',
    playerCount: [1, 2],
    supportedModes: ['single', 'local', 'party'],
    supportsAI: true,
    themeColor: '#34d399',
    artworkGlyph: 'XO',
    tags: ['starter', 'strategy', 'grid'],
    tutorialId: 'tutorial-tic-tac-toe',
    launchTier: 'milestone1',
  },
  {
    id: 'connect-4',
    name: 'Connect 4',
    category: 'board',
    shortDescription: 'Drop discs, read the board, and connect four.',
    description: 'A tense lane-control strategy game with fast AI turns and great hotseat pacing.',
    playerCount: [1, 2],
    supportedModes: ['single', 'local', 'party'],
    supportsAI: true,
    themeColor: '#60a5fa',
    artworkGlyph: '4',
    tags: ['strategy', 'family', 'columns'],
    tutorialId: 'tutorial-connect-4',
    launchTier: 'milestone1',
  },
  {
    id: 'checkers',
    name: 'Checkers',
    category: 'board',
    shortDescription: 'Capture, crown, and control the diagonals.',
    description: 'Traditional draughts with clean board readability and approachable local play.',
    playerCount: [1, 2],
    supportedModes: ['single', 'local', 'party'],
    supportsAI: true,
    themeColor: '#f59e0b',
    artworkGlyph: 'CK',
    tags: ['strategy', 'classic', 'board'],
    tutorialId: 'tutorial-checkers',
    launchTier: 'milestone1',
  },
  {
    id: 'reversi',
    name: 'Reversi',
    category: 'board',
    shortDescription: 'Flip chains and own the corners.',
    description: 'A deep positional board game with deterministic state, pass turns, and AI-ready logic.',
    playerCount: [1, 2],
    supportedModes: ['single', 'local', 'party'],
    supportsAI: true,
    themeColor: '#a78bfa',
    artworkGlyph: 'RV',
    tags: ['strategy', 'flip', 'classic'],
    tutorialId: 'tutorial-reversi',
    launchTier: 'milestone1',
  },
  {
    id: 'battleship',
    name: 'Battleship',
    category: 'board',
    shortDescription: 'Place, scan, and sink the enemy fleet.',
    description: 'Secret-grid battles with guided placement, hit tracking, and quick solo sessions.',
    playerCount: [1, 2],
    supportedModes: ['single', 'local', 'party'],
    supportsAI: true,
    themeColor: '#22d3ee',
    artworkGlyph: 'BS',
    tags: ['naval', 'guessing', 'grid'],
    tutorialId: 'tutorial-battleship',
    launchTier: 'milestone1',
  },
  {
    id: 'blackjack',
    name: 'Blackjack',
    category: 'card',
    shortDescription: 'Push your luck against the house.',
    description: 'Dealer rules, chip tracking, and fast solo or local sessions with readable card totals.',
    playerCount: [1, 4],
    supportedModes: ['single', 'local', 'party'],
    supportsAI: true,
    themeColor: '#f97316',
    artworkGlyph: '21',
    tags: ['cards', 'casino', 'quick'],
    tutorialId: 'tutorial-blackjack',
    launchTier: 'milestone1',
  },
  {
    id: 'solitaire',
    name: 'Solitaire',
    category: 'card',
    shortDescription: 'A calm solo card table with tableau and foundations.',
    description: 'Single-player Klondike-inspired solitaire with stock, waste, tableau, and foundation lanes.',
    playerCount: [1, 1],
    supportedModes: ['single'],
    supportsAI: false,
    themeColor: '#10b981',
    artworkGlyph: 'SA',
    tags: ['cards', 'solo', 'relaxing'],
    tutorialId: 'tutorial-solitaire',
    launchTier: 'milestone1',
  },
  {
    id: 'memory-match',
    name: 'Memory Match',
    category: 'party',
    shortDescription: 'Flip, remember, and score the most pairs.',
    description: 'Accessible local multiplayer pattern-matching with fast rounds and visible scoring.',
    playerCount: [1, 4],
    supportedModes: ['single', 'local', 'party'],
    supportsAI: false,
    themeColor: '#fb7185',
    artworkGlyph: 'MM',
    tags: ['memory', 'family', 'party'],
    tutorialId: 'tutorial-memory-match',
    launchTier: 'milestone1',
  },
  {
    id: 'chess',
    name: 'Chess',
    category: 'board',
    shortDescription: 'Full-board chess with legal moves, checkmate, and local play.',
    description: 'Classic chess now launches with rule-legal movement, move history, and lightweight AI turns.',
    playerCount: [1, 2],
    supportedModes: ['single', 'local', 'party'],
    supportsAI: true,
    themeColor: '#e5e7eb',
    artworkGlyph: 'CH',
    tags: ['strategy', 'classic', 'tactics'],
    tutorialId: 'tutorial-chess',
    launchTier: 'milestone2',
  },
  {
    id: 'hearts',
    name: 'Hearts',
    category: 'card',
    shortDescription: 'Take tricks carefully and avoid piling up penalty cards.',
    description: 'A streamlined hearts table with follow-suit rules, trick scoring, and rotating turns.',
    playerCount: [4, 4],
    supportedModes: ['single', 'local', 'party'],
    supportsAI: true,
    themeColor: '#fca5a5',
    artworkGlyph: 'HT',
    tags: ['cards', 'trick-taking', 'classic'],
    tutorialId: 'tutorial-hearts',
    launchTier: 'milestone2',
  },
  {
    id: 'crazy-eights',
    name: 'Crazy Eights',
    category: 'card',
    shortDescription: 'Match suit or rank, play wild eights, and shed your hand.',
    description: 'Fast family card action with discard-pile pressure, suit changes, and draw-pile recovery.',
    playerCount: [2, 4],
    supportedModes: ['single', 'local', 'party'],
    supportsAI: true,
    themeColor: '#fde047',
    artworkGlyph: 'CE',
    tags: ['cards', 'family', 'discard'],
    tutorialId: 'tutorial-crazy-eights',
    launchTier: 'milestone2',
  },
  {
    id: 'ludo',
    name: 'Ludo',
    category: 'board',
    shortDescription: 'Race tokens down the track, bounce rivals home, and finish first.',
    description: 'A streamlined ludo race with die rolls, captures, home stretches, and pass-and-play pacing.',
    playerCount: [2, 4],
    supportedModes: ['single', 'local', 'party'],
    supportsAI: true,
    themeColor: '#f87171',
    artworkGlyph: 'LU',
    tags: ['board', 'dice', 'race'],
    tutorialId: 'tutorial-ludo',
    launchTier: 'milestone2',
  },
  {
    id: 'backgammon',
    name: 'Backgammon',
    category: 'board',
    shortDescription: 'Roll, move, and bear off every checker before your opponent.',
    description: 'A compact backgammon-style race table with dice sequencing and checker movement decisions.',
    playerCount: [2, 2],
    supportedModes: ['single', 'local', 'party'],
    supportsAI: true,
    themeColor: '#c084fc',
    artworkGlyph: 'BG',
    tags: ['board', 'dice', 'race'],
    tutorialId: 'tutorial-backgammon',
    launchTier: 'milestone2',
  },
  {
    id: 'texas-holdem',
    name: 'Texas Hold\'em',
    category: 'card',
    shortDescription: 'Deal hole cards, reveal streets, and compare the best five-card hand.',
    description: 'A clear hold\'em showdown table for local sessions, community-card reveals, and hand ranking practice.',
    playerCount: [2, 4],
    supportedModes: ['single', 'local', 'party'],
    supportsAI: false,
    themeColor: '#ef4444',
    artworkGlyph: 'TH',
    tags: ['cards', 'poker', 'showdown'],
    tutorialId: 'tutorial-texas-holdem',
    launchTier: 'milestone2',
  },
  {
    id: 'trivia',
    name: 'Trivia',
    category: 'party',
    shortDescription: 'Local quiz rounds with quick-fire multiple choice scoring.',
    description: 'Answer curated questions, rotate turns, and keep score across a short trivia set.',
    playerCount: [1, 6],
    supportedModes: ['single', 'local', 'party'],
    supportsAI: false,
    themeColor: '#38bdf8',
    artworkGlyph: 'TQ',
    tags: ['party', 'quiz', 'knowledge'],
    tutorialId: 'tutorial-trivia',
    launchTier: 'milestone2',
  },
  {
    id: 'drawing-club',
    name: 'Drawing Club',
    category: 'party',
    shortDescription: 'Sketch lively prompts on a shared canvas and score the round.',
    description: 'A couch-friendly drawing game with prompt rotation, a live sketch pad, and manual score control.',
    playerCount: [2, 8],
    supportedModes: ['local', 'party'],
    supportsAI: false,
    themeColor: '#2dd4bf',
    artworkGlyph: 'DR',
    tags: ['party', 'drawing', 'creative'],
    tutorialId: 'tutorial-drawing-club',
    launchTier: 'milestone2',
  },
  {
    id: 'charades',
    name: 'Charades',
    category: 'party',
    shortDescription: 'Act out fast prompts, keep the pace up, and track every win.',
    description: 'A simple charades flow with rotating turns, prompt decks, and quick score marking.',
    playerCount: [2, 12],
    supportedModes: ['local', 'party'],
    supportsAI: false,
    themeColor: '#14b8a6',
    artworkGlyph: 'CH',
    tags: ['party', 'acting', 'prompts'],
    tutorialId: 'tutorial-charades',
    launchTier: 'milestone2',
  },
  {
    id: 'bluffing-room',
    name: 'Bluffing Room',
    category: 'party',
    shortDescription: 'Pass the device, hide the odd word, and catch the bluffer.',
    description: 'A local hidden-role prompt game with private reveals, table suspicion, and score-based rounds.',
    playerCount: [4, 8],
    supportedModes: ['local', 'party'],
    supportsAI: false,
    themeColor: '#f472b6',
    artworkGlyph: 'BR',
    tags: ['party', 'bluffing', 'deduction'],
    tutorialId: 'tutorial-bluffing-room',
    launchTier: 'milestone2',
  },
];

export const manifestById = Object.fromEntries(allGameManifests.map((manifest) => [manifest.id, manifest]));
